/**
 * \author SPDX-FileCopyrightText: 2022 Peter Poeschl <pp+ujt2208@nest-ai.de>
 *
 * \copyright SPDX-License-Identifier: GPL-2.0-or-later
 *
 * \file jamexp_gen.c
 * \brief Unit test program for jamexp.c generated by Bison from jamexp.y
 *
 * Test idea:
 * * assume non-generated jamexp.c is correct
 * * create tests for urj_jam_evaluate_expression() to exercise all productions
 * * use the same test vectors to validate syntax in jamexp.c generated from
 *   jamexp.y
 */

#include "jamexp_shrd.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "jamdefs.h"
#include "jamytab.h"

#include "tap/basic.h"

int main(void)
{
#if URJ_JAM_YYDEBUG
   const char *const env_URJ_JAM_YYDEBUG = getenv("URJ_JAM_YYDEBUG");
   urj_jam_yydebug
      = env_URJ_JAM_YYDEBUG && !strcmp(env_URJ_JAM_YYDEBUG, "1");
#endif
   plan(PLAN_TESTS);

   check__urj_jam_evaluate_expression();
}
